#!/usr/bin/env ruby
while true
  cmd = "th sample.lua cv/tomita-deep.t7 -gpuid -1 -primetext \"color \" -length 80 -temperature 3 -seed #{rand(60000)}"
  output = `#{cmd}`
  puts output.lines.first  
end
